version: "3"

services:
  database:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: angular_nest
      MYSQL_USER: 'root'
      MYSQL_ROOT_PASSWORD: 'root'
    volumes:
      - ./db:/var/lib/mysql
    ports:
      - 33066:3306